### ISSUE TITLE
v0.2.2 - plugin not showing up

### ISSUE THREAD

**Issue by StrikeAgainst** [ghermens/media2click#1]
I installed the plugin [according to documentation](https://docs.typo3.org/p/amazing/media2click/master/en-us/Administrator/Index.html) (although I'm not sure what point 3 is supposed to mean), but when creating a plugin type element, the plugin for this extension doesn't show up. I'm not quite experienced with Typo3, and I have no idea how to troubleshoot this.

Any help would be greatly appreciated. If required I can provide any data necessary to fix this situation.

**Comment by ghermens** [comment]
This extension doesn't provide an additional plugin, but alters the rendering of all external videos in the existing content elements, i.e. the textmedia content element.

**Comment by ghermens** [comment]
Regarding "point 3", take a look at the official TypoScript documentation, i.e.
https://docs.typo3.org/m/typo3/tutorial-typoscript-in-45-minutes/master/en-us/
https://docs.typo3.org/m/typo3/tutorial-templating/master/en-us/
https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Page/Index.html
