### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by NicGeb** [ghermens/media2click#11]
Typo3: 9.5.5
media2click: 1.3.5

I have a weird problem. 
I have activated the 'permanently enable'-Button at the host definition, an I also set plugin.media2click.enablePermanently = 1 in constants

In Frontend, the second Button shows up - but only with the default language. Any other language there is only the one button (Activate once). 

It would be great if anybody could point me in the right direction to get it working across all languages :)

**Comment by ghermens** [comment]
Hi NicGeb,

> Typo3: 9.5.5 media2click: 1.3.5

please update to TYPO3 10.4.21 / media2click 2.0.0 or at least TYPO3 9.5.31.

> I have a weird problem. I have activated the 'permanently enable'-Button at the host definition, an I also set plugin.media2click.enablePermanently = 1 in constants
> 
> In Frontend, the second Button shows up - but only with the default language. Any other language there is only the one button (Activate once).
> 
> It would be great if anybody could point me in the right direction to get it working across all languages :)

Did you you translate the host definitions?

Regards,
Gregor

**Comment by NicGeb** [comment]
Hi Gregor,

thanks for your reply.
Updating is long in planning, but a bit difficult atm.

Well, i did try to localize the host-folder, but when localizing the host entries as such it just produces copies no localization as such.
And it doesn't change anything in the frontend.

Regards 
Nicole

**Comment by ghermens** [comment]
> Well, i did try to localize the host-folder, but when localizing the host entries as such it just produces copies no localization as such.

Are these copies localized to your second or default language?

**Comment by NicGeb** [comment]
They're all localized to the default language

**Comment by ghermens** [comment]
You're working with admin privileges?
Localizing other data types on the same page works?

**Comment by NicGeb** [comment]
Yes, had no localization problem so far.

**Comment by NicGeb** [comment]
Weirdly though, I set up the extension on a dev instance of our site and that one runs on 9.5.28
There the 'permanently enable'-Button appears in any language without any problems and without having to localize the hosts.
Maybe it actually is a versions problem?!

**Comment by ghermens** [comment]
Please update and reopen the issue if the problem still exists.
