### ISSUE TITLE
Sorting of the host list 

### ISSUE THREAD

**Issue by crochelt** [ghermens/media2click#13]
You could add backend sorting to the host list plugin by changing media2click/Classes/Domain/Repository/HostRepository.php a bit:  

namespace Amazing\Media2click\Domain\Repository;

use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Extbase\Persistence\Repository;
use TYPO3\CMS\Extbase\Persistence\QueryInterface;

class HostRepository extends Repository {
    // Order by BE sorting
    protected $defaultOrderings = array(
        'sorting' => QueryInterface::ORDER_ASCENDING
    );

**Comment by ghermens** [comment]
Hi,
I added defaultOrderings to the repository.

As sorting in the flexform does not influence the sorting field of the host table, hosts will always be sorted in the FE by the sorting in the BE list module.
