### ISSUE TITLE
Copying and pasting content elements throws an uncaught TYPO3 exception

### ISSUE THREAD

**Issue by zenoussi** [ghermens/media2click#14]
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1438183881: TCA table tt_content ctrl['type'] is set to CType, but this field does not exist in the database of this table | UnexpectedValueException thrown in file /Users/xxxxxx/Sites/xxx/public/typo3/sysext/backend/Classes/Form/FormDataProvider/DatabaseRecordTypeValue.php in line 62. Requested URL: https://dev.xxxxxx.local/typo3/ajax/record/process?token=--AnonymizedToken--&CB[paste]=tt_content|145&CB[pad]=normal&CB[update][colPos]=1540-25&CB[update][sys_language_uid]=0

TYPO3 v11.5.15
EXT:container v2.0.1
EXT:content_defender v3.2.2
EXT:media2click v3.0.0 (v2.0.1, works fine!!!)
PHP: 7.4.21

Flotte Grüße
Ulli

**Comment by ghermens** [comment]
Which CType did you try to C&P? "iFrame with consent" or "Content with consent"?

**Comment by zenoussi** [comment]
all, including text or headline (standard ctypes)

**Comment by ghermens** [comment]
I just released version 3.0.1, which fixes a similar problem with translating content elements.
Please check if this solves your problem too ...

**Comment by zenoussi** [comment]
> I just released version 3.0.1, which fixes a similar problem with translating content elements. Please check if this solves your problem too ...

Yes, the version fixes my problem. Thanks very much! ✌🏼

**Comment by ghermens** [comment]
Thanks for  the feedback ...
