### ISSUE TITLE
Error under PHP 8

### ISSUE THREAD

**Issue by pixelpeter-gmbh** [ghermens/media2click#15]
Hello

thank you for your work with this extension.

I have found a bug that causes errors under PHP 8.0 / 8.1. 

`Tue, 20 Dec 2022 15:50:24 +0100 [ALERT] request="387c26ca56162" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 2022122014502290b18a47- Exception: PHP Warning: Undefined array key "enable2click" in typo3/public/typo3conf/ext/media2click/Classes/Resource/Rendering/YouTubeRenderer.php line 45, in file typo3/public/typo3/sysext/core/Classes/Error/ErrorHandler.php:137 - {"exception":"TYPO3\\CMS\\Core\\Error\\Exception: PHP Warning: Undefined array key \"enable2click\" in typo3/public/typo3conf/ext/media2click/Classes/Resource/Rendering/YouTubeRenderer.php line 45 in typo3/public/typo3/sysext/core/Classes/Error/ErrorHandler.php:137\nStack trace:\n#0 typo3/public/typo3conf/ext/media2click/Classes/Resource/Rendering/YouTubeRenderer.php(45): TYPO3\\CMS\\Core\\Error\\ErrorHandler->handleError(2, 'Undefined array...', `

Greetings

**Comment by ghermens** [comment]
Thanks, fixed in https://github.com/ghermens/media2click/commit/591e9a043f385a8592d95ef3e41c88dfa086152c
