### ISSUE TITLE
Preview-Image

### ISSUE THREAD

**Issue by icehawk-de** [ghermens/media2click#2]
We want to use this extension with vimeo videos and preview images. 
The Extension works fine. It generates the preview images in the folder /typo3temp/var/transient/

But the preview-image isn't visible. When I try to open the image directly, I get an error 403.

We found, that the folder /typo3tem/var/ is protected with a .htacces, installed from Typo3 itself. 

How can we unprotect these files, without to disable this security feature?

**Comment by ghermens** [comment]
The file in /typo3temp/var/transient/ is the original preview image as fetched from the vimeo server.
If this file is used directly in the rendered output, this means there has been no processing of the file during rendering, ie that the image is already in the perfect size for your usecase.

Please check in the Install Tool that image processing is working. If so, try to force processing of the image by changing the plugin.media2click.showPreviewImage.* constants.

**Comment by icehawk-de** [comment]
Thats it! Thanks a lot.
