### ISSUE TITLE
Alter table in backend not working

### ISSUE THREAD

**Issue by nannione** [ghermens/media2click#21]
If i run database compare in the backend i get the persistent message:

```
ALTER TABLE `tx_media2click_domain_model_host` CHANGE `placeholder` `placeholder` TEXT NOT NULL
Current value: placeholder TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`
```

**Comment by ghermens** [comment]
Please describe your environment, i.e.:

- TYPO3 version
- PHP version
- database server version
- media2click version
- ...

**Comment by nannione** [comment]
Typo3 12.4.4
PHP 8.2.0alpha1
MySQL 8.0.22
media2Click dev-main

**Comment by ghermens** [comment]
I can't reproduce your problem (with PHP 8.2.8, MariaDB 10.3.39). Maybe MySQL is more case sensitive here?
Please try if https://github.com/ghermens/media2click/commit/407c72568926024c2f2bc2364c64cdcb99824392 helps ...

**Comment by ghermens** [comment]
Closed with no feedback. Please reopen if necessary ...
