### ISSUE TITLE
YouTubeRenderer.php settings.title cause error with PHP 8.1 

### ISSUE THREAD

**Issue by horst-creationell** [ghermens/media2click#23]
TYPO3 Version 12.4.10
PHP 8.1.27
Line of the error in PHP file: 158 - 'title' => $options['title'],

Reason of error: debug output does not show a property named title in Frontend 

**output of <f:debug>:**
 array:11 [▼
  "class" => "embed-responsive-item"
  "file" => TYPO3\CMS\Core\Resource\FileReference {#28904 ▶}
  "additionalConfig" => array:4 [▶]
  "cropVariant" => "default"
  "no-cookie" => "1"
  "api" => "0"
  "enable2click" => "1"
  "placeholderContent" => array:5 [▶]
  "autoplay" => 0
  "controls" => 1
  "allow" => "fullscreen"
]
PHP Error message:
PHP Warning: Undefined array key "title" in /vendor/amazing/media2click/Classes/Resource/Rendering/YouTubeRenderer.php line 158

Temporary Solution in YouTubeRenderer.php:
'title' => $options['title'] ?? '',

**Comment by ghermens** [comment]
Thanks, resolved in 7ad369f
