### ISSUE TITLE
Extension not enabled after install

### ISSUE THREAD

**Issue by okroener** [ghermens/media2click#24]
Hello @markussoeth  @ghermens ,

I really like yyour extension. However, is it still the case, that thex EXT is not enabled after install?

For me, it makes sense to enable that anytime. Or has this changed in the meantime?

Best,

Oliver

**Comment by ghermens** [comment]
Hi @okroener ,
this behaviour is intentional:
* You can complete your configuration before enabling the extension.
* Multi site installations are not broken just by installing the  extension.
hth
Gregor
