### ISSUE TITLE
Preview Image 2

### ISSUE THREAD

**Issue by icehawk-de** [ghermens/media2click#3]
Typo3 9LTS

I now try to use this Extension with youtube videos.
Everything works fine except the preview images.

I had a similar problem with vimeo videos in this ticket: https://github.com/ghermens/media2click/issues/2

I tried the same constants, but no preview is rendered. Image rendering works fine.
This time I don't have any errors in the console.

```
plugin.media2click {
  enable = 1
  showPreviewImage {
    maxWidth = 768
    maxHeight = 432
  }
}
```

I get this code. The style-Tag is empty. (The preview image of vimeo is shown here as a background-image)
```
<div class="media2click-placeholder media2click-haspreview" style="">
  <div class="media2click-placeholder-inner">
  ...
  </div>
</div>
```

Whats now my problem?
Thanks

**Comment by ghermens** [comment]
I'm unable to reproduce your problem here.

- Could this be related to the videos you want to include? Can you give me some YT-URLs please?

- Are the previews downloaded to typo3temp/transient/youtube_*.jpg?

**Comment by icehawk-de** [comment]
At the moment I develop local with a composer installation of Typo3 9.5.19

A youtube-link is: https://www.youtube.com/watch?v=FqKgi5ferqA

I have a Keitel_Haus_Kinospot_2019.youtube file in fileadmin.

I don't have youtube_*.jpg files in this folder: typo3temp/transient/ or typo3temp/var/transient/. These folders do not exist.

**Comment by ghermens** [comment]
> A youtube-link is: https://www.youtube.com/watch?v=FqKgi5ferqA

Works here just fine...

> I don't have youtube_*.jpg files in this folder: typo3temp/transient/ or typo3temp/var/transient/. These folders do not exist.

Temporary folder for preview images is TYPO3\CMS\Core\Core\Environment::getVarPath() . '/transient/', which is  typo3temp/var/transient/ in default installations. This directory is created if not present when downloading  the preview image. So either the download is not triggered at all, or the directory is located somewhere else in your installation.

Does this work for Vimeo videos? The preview images use the same directory...

**Comment by icehawk-de** [comment]
Thanks für your support.

I found the youtube_*.jpg files.
I have a composer installation of Typo3. The /trancient/ folder is outside /typo3temp/. The expected files are in this folder.
I've done a symlink into the /typo3temp/ folder. 

But there is still no preview image in the Frontend. (Cleared all caches)

I will also test it on a "non" composer version and give you a feedback.

**Comment by icehawk-de** [comment]
Tested on an "non" composer version.
Everything works fine an as expected.

It seems to be a problem only with a composer installation.

**Comment by ghermens** [comment]
I got this sorted out:
For the IMG_RESOURCE cObject to work, the downloaded image has to be inside Environment::getPublicPath().
I just uploaded new version 0.2.5 ...

**Comment by ftrojahn** [comment]
Just a note: due to the use of TYPO3\CMS\Core\Core\Environment the extension version 0.2.5 since commit 8373344f is not working in TYPO3 8.7 - had to use 0.2.4.
