### ISSUE TITLE
Reversed templateRootPath and layoutRootPath in MediaElements.typoscript

### ISSUE THREAD

**Issue by davkraid** [ghermens/media2click#5]
Hi,

first of all, thanks for your extension! But there is a little bug in the MediaElements.typoscript file. The constants for templateRootPath and layoutRootPath are reversed.

![2021-02-25_12-29](https://user-images.githubusercontent.com/264782/109147707-9af3c000-7765-11eb-9bd1-0c2728cf777f.png)

Kind regards
David

**Comment by ghermens** [comment]
Hi David,
thanks, nice catch...
Gregor
