### ISSUE TITLE
Changing default placeholder texts

### ISSUE THREAD

**Issue by icehawk-de** [ghermens/media2click#8]
Is there an easy way to change this text? I only want to edit this text.

![Opera Momentaufnahme_2021-05-05_142558_p581623 webspaceconfig de](https://user-images.githubusercontent.com/19264337/117140754-0aada900-adae-11eb-924d-e24b89e1a561.png)

**Comment by ghermens** [comment]
https://docs.typo3.org/p/amazing/media2click/1.3/en-us/Administrator/Index.html#if-individual-placeholder-content-or-permanent-activation-is-required
