### ISSUE TITLE
No processed files

### ISSUE THREAD

**Issue by icehawk-de** [ghermens/media2click#9]
I had a similar problem like: https://github.com/ghermens/media2click/issues/2

In the constants I have:
```
plugin.media2click {
  enable = 1
  enablePermanently = 1
  storagePid = 102
  privacyPid = 13
  showPreviewImage {
    maxWidth = 768
    maxHeight = 432
  }
}
```
Some of my preview-images won't be rendered and the bg-image shows to "/typo3temp/var/transient/".

So I took a look at the picture. It has the following sizes 320x180 Pixel. So the Imageprocessor won't work, because the picture is smaller then the sizes in the constants (nothing to do!).

Is there the possibility to copy the image, if its smaller than the constant sizes, to the _proccesed_ folder and use it?

**Comment by ghermens** [comment]
Which versions of TYPO3 and media2click? TER or composer installation?

**Comment by icehawk-de** [comment]
Its a Typo3 10.4.17 and a TER installation.

**Comment by ghermens** [comment]
I'm unable to reproduce your situation. Please send an example video url ...

**Comment by icehawk-de** [comment]
https://www.youtube.com/watch?v=qW90K6IzG-U

The Downloaded-Image is 380 x 180 px.

**Comment by ghermens** [comment]
Still not able to reproduce. The placeholder tag is rendered as:

`<div class="media2click-placeholder media2click-placeholder-video media2click-haspreview" style="width:200px;height:113px;background-image:url(/typo3temp/assets/_processed_/e/a/csm_youtube_70a7575c1e123859ccee67a7f0963bf4_21c7d01f31.jpg);" data-host="YouTube">...</div>`

**Comment by icehawk-de** [comment]
Thats funny. I get:
<div class="media2click-placeholder media2click-placeholder-video media2click-haspreview" style="background-image:url(/typo3temp/var/transient/youtube_70a7575c1e123859ccee67a7f0963bf4.jpg);" data-host="YouTube">...</div>

And the image in the typo3temp folder has 380 x 180 px. Tried several times.

https://www.youtube.com/watch?v=XfVtFnwBikc
This Video is OK. I get a 1280 x 720 px image in the typo3temp folder and a processed background-image:
background-image:url(/typo3temp/assets/_processed_/2/a/csm_youtube_acfaca943b3ffa99ced3fa631470bcfb_8cb6cd6c8f.jpg);

**Comment by ghermens** [comment]
Your placeholder style has no width/height at all.
Do you override anything related to media in EXT:fluid_styled_content templates?

**Comment by icehawk-de** [comment]
Nope. The FSC for textmedia is almost original. We have only added some bootstrap classes.

You have tested with the first video? https://www.youtube.com/watch?v=qW90K6IzG-U
Whats your size of the preview-image in the /typo3temp/var/transient/ folder?

**Comment by ghermens** [comment]
I tested with your video and constants. Downloaded file is 380x180.

**Comment by icehawk-de** [comment]
And you get a preview-image?

Is it possible that you have activated upscaling in the Install-Tool?
[GFX][processor_allowUpscaling]

We use "false".

**Comment by ghermens** [comment]
Disableing upscaling makes no difference here.

**Comment by icehawk-de** [comment]
When I change:
```
showPreviewImage {
  maxWidth = 768
  maxHeight = 432
}
```
to
```
showPreviewImage {
    maxWidth = 319
    maxHeight = 179
  }
```
The images are rendered and shown as preview.

**Comment by ghermens** [comment]
I just released version 1.3.5. Please check if this solves your problems...

**Comment by icehawk-de** [comment]
As soon as the TER will update I give you an update.

**Comment by icehawk-de** [comment]
Just updated. It works excellent! Problem solved.
Thanks a lot.
